### ISSUE TITLE
[FEATURE] Auto merge の追加

### ISSUE THREAD

**Issue by matumoto1234** [PandD-Aizu/Minge2021Winter_Team3#21]
## 提案の詳細

Approve されたら自動的にマージしてくれるようにする

## 動機

あったらうれしいよね

つけるかつけないかはこのコメントで議論しましょう

プルリクエストをなにもないので、GO サインが出たら設定を変更してこの issue を閉じます

**Comment by matumoto1234** [comment]
とりあえずつけていいって人はこのメッセージに 👍 を
過半数を超えたら変更します

**Comment by matumoto1234** [comment]
しまった
これ全体的な設定で変更するものではなく、個々のプルリクエストで行うものでした
ということで、プルリクエストが出たときに担当者が自動マージしてください 🙇 

参考 ⬇️ 
- https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request

**Comment by suzakutakumi** [comment]
OK
