### ISSUE TITLE
[FEATURE] ||, && を or, and にする（宗教）

### ISSUE THREAD

**Issue by matumoto1234** [PandD-Aizu/Minge2021Winter_Team3#53]
## 提案の詳細

||, && を or, and にする

なんだったら、`!` を `not` にしてもいいかも（宗教）

## 動機

https://zenn.dev/kariya_mitsuru/articles/f7776a1a1acb70

**Comment by suzakutakumi** [comment]
賛成です

**Comment by matumoto1234** [comment]
たぶんこれでいけると思う
 
- `&&` を `and` に置換する
`grep -e '&&' -rl ./* | sort | xargs sed -i -E -e "s/(| )&&(| )/ and /g"`

- `||` を `or` に置換する
`grep -e '||' -rl ./* | sort | xargs sed -i -E -e "s/(| )||(| )/ or /g"`

`sort` はあってもなくてもお好みです

`xargs...` 以降を無くした `grep -e '||' -rl ./* | sort` を実行すると対象のファイル達がソートされて見やすく表示されます

**Comment by id-isymhrk** [comment]
それって何のためのgrepですか

**Comment by matumoto1234** [comment]
ファイルの中から `&&` と `||` を検索して、sed コマンドで置換するようの `grep` になるかな
いい感じの方法がないか調べたら出てきたので、それをコピペしました
ちょっと間違ってるかもなので、あとで編集して正しておきます 🙇‍♂️

**Comment by id-isymhrk** [comment]
そんな便利なものがあったんですね。知りませんでした（調べるの怠けました）
わざわざありがとうございます！
