### ISSUE TITLE
[FEATURE] クレジットシーンの追加

### ISSUE THREAD

**Issue by id-isymhrk** [PandD-Aizu/Minge2021Winter_Team3#59]
## 提案の詳細
クレジットシーンを作成し、タイトルから選択したときに遷移できるようにする。

## 動機
Siv3Dのライセンス表記のため。
今回、BGMも借用する（予定）ので、たとえフリー素材でもここで表記した方が無難かと思います。

## その他
製作者である自分たちのハンドルネームも記述しても良いかもしれません。

**Comment by suzakutakumi** [comment]
F1キーを押すとSiv3Dのライセンスが出るのでいらないかも
