### ISSUE TITLE
[FEATURE] シーンのクラステンプレートの設計

### ISSUE THREAD

**Issue by suzakutakumi** [PandD-Aizu/Minge2021Winter_Team3#9]
## 提案の詳細
必要なシーンのクラスのテンプレートを作成する

## 動機
これを最初にやると、git管理がしやすい!

## 順序
1. シーンをリストアップする
2. シーンの定義をどこでやるかなどを決める
3. シーンのテンプレートを作る

**Comment by id-isymhrk** [comment]
これ古いissueだしCloseしても良いかと思うのですが

**Comment by suzakutakumi** [comment]
seyana
